### PR TITLE
Added: subscription functional

### LINKED ISSUE #97: Implement subreddits subscription functionality
As a user I want to be able to subscribe to the specific subreddit. I also want to be able to unsubscribe anytime.

## AC
The user is able to subscribe/unsubscribe to specific subreddit.
Tests code coverage > 70%

### LINKED ISSUE #98: Show subreddit subscribers amount
## Description
As a user, I want to see how many subscribers specific subreddit has.

## Tech tips:
Consider setting up indexes.

## Relates to:
https://github.com/JR-Abstract/reddit-clone-abstract/issues/97

## AC
User is able to see amount of subscribers of a specific subreddit.
Tests code coverage > 70%

### PR DESCRIPTION
**Pull request by Y-Maxym**
I didn't see that there are separate tasks for adding the number of subscriptions to a subreddit. I only saw them after I had already done them, I m sorry.

This task adds the functionality: 
1. Subscribe/unsubscribe from a subreddit 
2. View subscribers of the subreddit 
3. View the number of subscribers of the subreddit

### CODE REVIEW

**Review by aleos-dev — APPROVED** [review]
Great job, Max. But you should fetch the latest changes from the dev branch as your version has old data.

**Comment by Y-Maxym** [comment]
> Great job, Max. But you should fetch the latest changes from the dev branch as your version has old data.

I think all the changes from the dev are in there

**Comment by aleos-dev** [comment]
> > Great job, Max. But you should fetch the latest changes from the dev branch as your version has old data.
> 
> I think all the changes from the dev are in there

Okay, than why are you adding this script to the dev branch?
Screenshot from 2024-03-25 20-29-50

**Comment by Y-Maxym** [comment]
> > > Great job, Max. But you should fetch the latest changes from the dev branch as your version has old data.
> > 
> > 
> > I think all the changes from the dev are in there
> 
> Okay, than why are you adding this script to the dev branch? Screenshot from 2024-03-25 20-29-50

This is how merge works, when you do it, all changes are highlighted as new changes
You could try doing a merge
image

**Comment by aleos-dev** [comment]
> This is how merge works, when you do it, all changes are highlighted as new changes You could try doing a merge 

It's becoming interesting. I got how merge works) Anyway, you've implemented the Flyway migration. Now, you're merging the script named postgres_DDL.sql into the dev branch, which was renamed to V1__*.sql. Can you explain me it, why we should keep both of it?

**Comment by Y-Maxym** [comment]
> > > This is how merge works, when you do it, all changes are highlighted as new changes You could try doing a merge > > It's becoming interesting. Anyway, you've implemented the Flyway migration. Now, you're merging the script named postgres_DDL.sql into the dev branch, which was renamed to V1__*.sql. Can you explain to me it, why we should keep both of it?

The reason I left the old file is to avoid errors later, in case it is still useful and my commit deletes it and I have to go back to previous commits to restore it

**Comment by aleos-dev** [comment]
So, do you think it is proper to leave it as is and merge it into the dev branch?

**Comment by aleos-dev** [comment]
Regardless, I've learned something valuable from this situation)

**Comment by Y-Maxym** [comment]
> So, do you think it is proper to leave it as is and merge it into the dev branch?

What other problems do you see besides this one?

**Comment by aleos-dev** [comment]
I just noticed that there are duplicates in your pull request. Initially, I thought that you hadn't refreshed the dev changes. However, as we discovered, you did merge new data into your branch, but there can be some tricky situations if files were deleted or renamed.

**Pull request merged**
